//PER QUESTA ESERCITAZIONE DOBBIAMO REPERIRE UNA TABELLA ASCII
//QUESTA RIPORTA LA TRADUZIONE PER TUTTI I NOSTRI CARATTERI! AD ESEMPIO a CORRISPONDE AL CARATTERE NUMERO 97!
//POSSIAMO ACCEDERE A QUESTA TRAMITE IL COMANDO ascii DAL NOSTRO TERMINALE! z CORRISPONDE AL CARATTERE 122!
//N.B. IN SEDE HO CHIESTO DI AGGIORNARE IL PACCHETTO ascii, NEL CASO SUL TUO DISPOSITIVO NON DOVESSE FUNZIONARE
//     PUOI ACCEDERCI TRAMITE IL COMANDO man ascii (man man PER TUTTO IL RESTO! C:)
#include <unistd.h>

void	ft_print_alphabet(char a)

{
//PER PRIMA COSA DEFINIAMO A QUALE CARATTERE DOBBIAMO ASSOCIARE a
//AVREMMO POTUTO SCRIVERE ANCHE 'a'
	a = 97;
//TRAMITE while CREIAMO UN LOOP DA QUANDO a E' MINORE DI 'z' IMPONENDO CHE NON POTRA' MAI SCENDERE SOTTO IL VALORE 97
//L'OPERATORE LOGICO && (AND) IMPONE CHE ENTRAMBE LE PARTI DEBBANO ESSERE VERE O FALSE PER OPERARE
//				                    					 ES: (<PARTE A> && <PARTE B>)
//L'OPERATORE LOGICO || (OR) IMPONE CHE BASTA UNA DELLE DUE PARTI PER OPERARE
		while (a <= 122 && a >= 97)

		{
		write(1, &a, 1);
		a++;
//QUI INCREMENTIAMO IL VALORE DI a ALLA FINE DI OGNI CICLO DEL LOOP
//LA VERSIONE ESTESA E' a += 1;
//RICORDATI CHE DEVE RESTARE DENTRO IL NOSTRO while!
		}
}

/*
int	main()
{
	ft_print_alphabet(' ');
		return (0);
}
*/
//M3DD1J
