#include <unistd.h>
//AL CONTRARIO DI char UTILIZZIAMO int PER DEFINIRE NUMERI INTERI
void	ft_is_negative(int n)

{
//UTILIZZIAMO if PER IMPORRE ALLA FUNZIONE DI OPERARE SOLO 'SE'
//SE IL VALORE DI n E' MAGGIORE UGUALE DI 0 ESEGUI >> SCRIVI IL CARATTERE " P " 
	if(n >= 0)
	{
		write(1,"P", 1);
	}
//AL CONTRARIO UTILIZZIAMO else PER DETERMINARE CIO' CHE ACCADRA' NEL CASO CHE L'ESPRESSIONE if PRECEDENTE SIA FALSA
//RICORDA CHE else SIGNIFICA invece
//QUINDI STIAMO DICENDO:
//SE n E' MAGGIORE O UGUALE A 0 SCRIVI P INVECE SE n E' MINORE DI 0 SRIVI N
	else
		write(1,"N", 1);
}

/*
int	main()

{
	ft_is_negative(-1);
	return 0;
}
*/
//M3DD1J
